### PR TITLE
Support Faraday's timeout options

### PR DESCRIPTION
**Pull request by ma2gedev**
I would like to control Faraday's timeout options, so this pull request supports both open_timeout and timeout options.

This pull request is based on #46's branch.
So I will rebase master branch after #46 was merged If this pull request was accepted.

### CODE REVIEW

**Comment by kyanny** [comment]
Maybe this is actual diff from #46 ?
https://github.com/ma2gedev/sbpayment.rb/compare/feature/control_retry...ma2gedev:feature/timeout_options

👍 Code looks good to me. cc @banyan @kachick

**Comment by ma2gedev** [comment]
> Maybe this is actual diff from #46 ?

Yes! Thank you for your concern.

**Comment by ma2gedev** [comment]
Thanks for merging #46. I'll execute `git rebase master`, please wait.

**Comment by ma2gedev** [comment]
Just rebased!

**Comment by kyanny** [comment]
👍 Thank you for your contribution @ma2gedev !

**Comment by kyanny** [comment]
@ma2gedev 
Released v0.8.0
https://github.com/quipper/sbpayment.rb/releases/tag/v0.8.0
https://rubygems.org/gems/sbpayment/versions/0.8.0

**Comment by ma2gedev** [comment]
Thank you!! 👍

**Pull request merged**
