### PR TITLE
Remove sps_transaction_id

### PR DESCRIPTION
**Pull request by banyan**
image

### CODE REVIEW

**Comment by kachick** [comment]
This PR is changing `ST02-00201-405`. Could you add the correct screenshot?

**Comment by banyan** [comment]
sorry my screenshot was wrong. this is correct.

image

**Comment by kachick** [comment]
Thank you! :+1:

**Comment by banyan** [comment]
Released as https://rubygems.org/gems/sbpayment/versions/0.2.2

**Pull request merged**
