### PR TITLE
Implement webcvs read payment result API (MG01-00101-701)

### PR DESCRIPTION
**Pull request by kyanny**
Implements webcvs payment result API (MG01-00101-701).

Unfortunately, SBPS's sandbox (API type) seems not working well for webcvs API payment type (payment API result returns "70122999" error code)

### CODE REVIEW

**Comment by banyan** [comment]
LGTM :+1:

**Comment by kyanny** [comment]
Thank youuuuu :cactus:

**Comment by kachick** [comment]
@kyanny Thank you! The released version 0.4.2 contains this PR :sunglasses:

**Comment by kyanny** [comment]
:tada:

**Pull request merged**
